"""Outbound connector ports for Data Mover transfers."""

from __future__ import annotations

from app.connectors.base import (
    BatchWriteResult,
    CatalogBrowser,
    CatalogPage,
    CatalogReader,
    ColumnSchema,
    ConnectionHealth,
    ConnectionTester,
    Connector,
    DatasetProvisioner,
    DestinationInspector,
    DestinationManifest,
    DestinationRowCounter,
    DestinationSchemaInspector,
    DestinationWriter,
    LoadSession,
    ObjectSchema,
    ObjectSchemaInspector,
    ProviderCapabilities,
    RegisteredConnector,
    RemoteNamespace,
    RemoteObject,
    RowCounter,
    SourceReader,
    TransferBatch,
)
from app.connectors.errors import ConnectorError, TransferErrorCode
from app.connectors.locators import (
    CsvUploadLocator,
    DefinitionSnapshot,
    FoundryDatasetFilesLocator,
    FoundryUploadLocator,
    Locator,
    PostgresTableLocator,
    WritePolicy,
    parse_locator,
    parse_snapshot,
    parse_write_policy,
)
from app.connectors.registry import (
    catalog_browser_for,
    catalog_reader_for,
    connection_tester_for,
    destination_writer_for,
    object_schema_inspector_for,
    row_counter_for,
    source_reader_for,
)

__all__ = [
    "BatchWriteResult",
    "CatalogBrowser",
    "CatalogPage",
    "ColumnSchema",
    "ConnectionHealth",
    "ConnectionTester",
    "Connector",
    "CatalogReader",
    "catalog_browser_for",
    "catalog_reader_for",
    "connection_tester_for",
    "ConnectorError",
    "CsvUploadLocator",
    "DefinitionSnapshot",
    "DestinationManifest",
    "DestinationInspector",
    "DestinationRowCounter",
    "DestinationSchemaInspector",
    "DestinationWriter",
    "destination_writer_for",
    "DatasetProvisioner",
    "FoundryDatasetFilesLocator",
    "FoundryUploadLocator",
    "LoadSession",
    "Locator",
    "ObjectSchema",
    "ObjectSchemaInspector",
    "object_schema_inspector_for",
    "PostgresTableLocator",
    "ProviderCapabilities",
    "RegisteredConnector",
    "RemoteNamespace",
    "RemoteObject",
    "RowCounter",
    "row_counter_for",
    "SourceReader",
    "source_reader_for",
    "TransferBatch",
    "TransferErrorCode",
    "WritePolicy",
    "parse_locator",
    "parse_snapshot",
    "parse_write_policy",
]
