"""Compatibility re-exports for versioned domain locator contracts."""

from app.domain.locators import (
    DATASET_RID_PATTERN,
    FOUNDATION_FILE_PATTERN,
    IDENTIFIER_PATTERN,
    UUID_PATTERN,
    CsvUploadLocator,
    DefinitionSnapshot,
    FoundryDatasetFilesLocator,
    FoundryReplaceFilePolicy,
    FoundryUploadLocator,
    Locator,
    PostgresAppendPolicy,
    PostgresReplacePolicy,
    PostgresTableLocator,
    PostgresUpsertPolicy,
    WritePolicy,
    normalize_foundry_source_paths,
    parse_locator,
    parse_snapshot,
    parse_write_policy,
    postgres_table,
    validate_locator,
)

__all__ = [
    "DATASET_RID_PATTERN",
    "FOUNDATION_FILE_PATTERN",
    "IDENTIFIER_PATTERN",
    "UUID_PATTERN",
    "CsvUploadLocator",
    "DefinitionSnapshot",
    "FoundryDatasetFilesLocator",
    "FoundryReplaceFilePolicy",
    "FoundryUploadLocator",
    "Locator",
    "PostgresAppendPolicy",
    "PostgresReplacePolicy",
    "PostgresTableLocator",
    "PostgresUpsertPolicy",
    "WritePolicy",
    "normalize_foundry_source_paths",
    "parse_locator",
    "parse_snapshot",
    "parse_write_policy",
    "postgres_table",
    "validate_locator",
]
